<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
	  <RootNamespace>Gims.Core</RootNamespace>
	  <AssemblyName>Gims.Core</AssemblyName>
  </PropertyGroup>

	<PropertyGroup>
		<EnableNETAnalyzers>false</EnableNETAnalyzers>
	</PropertyGroup>
	
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Common\Enums\" />
    <Folder Include="Common\Interfaces\" />
    <Folder Include="Common\Extensions\" />
    <Folder Include="Common\ValueObjects\" />
    <Folder Include="Customer\" />
    <Folder Include="Claims\" />
    <Folder Include="Billing\" />
    <Folder Include="Report\" />
    <Folder Include="SysMan\Pages\" />
  </ItemGroup>

  <ItemGroup>
	  <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.11" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.11">
	    <PrivateAssets>all</PrivateAssets>
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.11" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.11" />  
  </ItemGroup>



</Project>
