<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Configuration\" />
    <Folder Include="Layout\" />
    <Folder Include="Modules\Quotation\Components\" />
    <Folder Include="Modules\Quotation\Config\" />
    <Folder Include="Modules\Quotation\Pages\" />
    <Folder Include="Modules\Risk\" />
    <Folder Include="Modules\Policy\" />
    <Folder Include="ModuleConfigProvider\" />
    <Folder Include="Modules\SysMan\Services\" />
    <Folder Include="Services\" />
    <Folder Include="Pages\" />
    <Folder Include="Sidebar\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Gims.Contracts\Gims.Contracts.csproj" />
    <ProjectReference Include="..\Gims.Core\Gims.Core.csproj" />
    <ProjectReference Include="..\Gims.Infrastructure\Gims.Infrastructure.csproj" />
  </ItemGroup>



</Project>
