<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
  </PropertyGroup>

  <PropertyGroup>
	<EnableNETAnalyzers>false</EnableNETAnalyzers>
  </PropertyGroup>
	
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="EF\Configurations\SysMan\Seed\Modules\" />
    <Folder Include="EF\Configurations\SysMan\Seed\SubModules\" />
    <Folder Include="Logging\" />
    <Folder Include="External\" />
    <Folder Include="Migrations\" />
    <Folder Include="SysManPersistence\" />
    <Folder Include="Repositories\" />
    <Folder Include="Storage\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Gims.Contracts\Gims.Contracts.csproj" />
    <ProjectReference Include="..\Gims.Core\Gims.Core.csproj" />
  </ItemGroup>

  </Project>
