<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Gims.App\Gims.App.csproj" />
    <ProjectReference Include="..\Gims.Contracts\Gims.Contracts.csproj" />
    <ProjectReference Include="..\Gims.Core\Gims.Core.csproj" />
    <ProjectReference Include="..\Gims.Infrastructure\Gims.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Modules\SysMan\AccessControl\Permission\" />
    <Folder Include="Modules\SysMan\AccessControl\Users\" />
    <Folder Include="Modules\SysMan\Products\" />
    <Folder Include="Modules\SysMan\WorkFlow\" />
    <Folder Include="Modules\Workspace\" />
  </ItemGroup>

  <ItemGroup>
		<PackageReference Include="Microsoft.FluentUI.AspNetCore.Components" Version="4.7.0" />
		<PackageReference Include="Unity" Version="5.11.10" />
	</ItemGroup>
	
</Project>
